# Generated by Django 4.1.7 on 2023-03-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.IntegerField()),
                ('Number', models.IntegerField()),
                ('Price_Total', models.IntegerField()),
                ('Status', models.IntegerField()),
            ],
        ),
    ]
