# Generated by Django 4.1.7 on 2023-03-31 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_category_url_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Order_Detail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.orderdetail'),
            preserve_default=False,
        ),
    ]
