# Generated by Django 4.1.7 on 2023-04-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_category_url_image_alter_category_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='Price',
        ),
        migrations.AddField(
            model_name='order',
            name='Price',
            field=models.IntegerField(default=29000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='Url_Image',
            field=models.ImageField(default=None, upload_to='home/static/img'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Url_Image',
            field=models.ImageField(default=None, upload_to='home/static/img'),
        ),
    ]
