# Generated by Django 4.1.7 on 2023-04-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_orderproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='Address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='Number_Phone',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
